#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'optparse'
require 'rnes'

options = ARGV.getopts('h', 'help', 'log:')
log_file_path = options['log']
args = ARGV.parse!
help_message = "Usage: #{$PROGRAM_NAME} [options] <FILE>"
if options['h'] || options['help']
  puts help_message
  exit
end

path = args.first
unless path
  abort help_message
end

io = File.binread(path)
bytes = io.bytes
emulator = Rnes::Emulator.new(log_file_path: log_file_path)
emulator.load_rom(bytes)
emulator.run
